basePath: /
definitions:
  usecase.LoginOutput:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
  title: B8boost API
  version: "1.0"
paths:
  /login:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecase.LoginOutput'
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: login with telegram
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
